/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutGenerateImport } from './routes/_layout/generate'
import { Route as LayoutSeedImport } from './routes/_layout/$seed'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGenerateRoute = LayoutGenerateImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSeedRoute = LayoutSeedImport.update({
  id: '/$seed',
  path: '/$seed',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/$seed': {
      id: '/_layout/$seed'
      path: '/$seed'
      fullPath: '/$seed'
      preLoaderRoute: typeof LayoutSeedImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/generate': {
      id: '/_layout/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof LayoutGenerateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutSeedRoute: typeof LayoutSeedRoute
  LayoutGenerateRoute: typeof LayoutGenerateRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSeedRoute: LayoutSeedRoute,
  LayoutGenerateRoute: LayoutGenerateRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/$seed': typeof LayoutSeedRoute
  '/generate': typeof LayoutGenerateRoute
  '/': typeof LayoutIndexRoute
}

export interface FileRoutesByTo {
  '/$seed': typeof LayoutSeedRoute
  '/generate': typeof LayoutGenerateRoute
  '/': typeof LayoutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/$seed': typeof LayoutSeedRoute
  '/_layout/generate': typeof LayoutGenerateRoute
  '/_layout/': typeof LayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/$seed' | '/generate' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$seed' | '/generate' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/$seed'
    | '/_layout/generate'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/$seed",
        "/_layout/generate",
        "/_layout/"
      ]
    },
    "/_layout/$seed": {
      "filePath": "_layout/$seed.tsx",
      "parent": "/_layout"
    },
    "/_layout/generate": {
      "filePath": "_layout/generate.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
